// src/components/styles.js
const styles = {
    container: {
        padding: '20px',
        maxWidth: '800px',
        margin: '0 auto',
        backgroundColor: '#f1f3f5',
        borderRadius: '8px',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    },
    header: {
        fontSize: '24px',
        marginBottom: '20px',
        textAlign: 'center',
        color: '#343a40',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '5px',
    },
    label: {
        fontSize: '16px',
        fontWeight: 'bold',
        color: '#343a40',
    },
    select: {
        padding: '8px',
        fontSize: '14px',
        borderRadius: '5px',
        border: '1px solid #ced4da',
        color: '#343a40',
        backgroundColor: '#fff',
        transition: 'border-color 0.2s',
        '&:focus': {
            borderColor: '#007bff',
            outline: 'none',
        },
    },
    fileInput: {
        padding: '8px 0',
    },
    input: {
        padding: '8px',
        fontSize: '14px',
        borderRadius: '5px',
        border: '1px solid #ced4da',
        color: '#343a40',
        transition: 'border-color 0.2s',
        '&:focus': {
            borderColor: '#007bff',
            outline: 'none',
        },
    },
    mappingSection: {
        marginTop: '20px',
        padding: '10px',
        backgroundColor: '#fff',
        borderRadius: '6px',
        boxShadow: '0 1px 4px rgba(0, 0, 0, 0.05)',
    },
    subHeader: {
        fontSize: '20px',
        marginBottom: '10px',
        color: '#343a40',
    },
    submitButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: '#fff',
        backgroundColor: '#28a745',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        marginTop: '20px',
        transition: 'background-color 0.2s, transform 0.1s',
        '&:hover': {
            backgroundColor: '#218838',
            transform: 'translateY(-1px)',
        },
        '&:disabled': {
            backgroundColor: '#6c757d',
            cursor: 'not-allowed',
        },
    },
    error: {
        marginTop: '20px',
        padding: '10px',
        backgroundColor: '#f8d7da',
        color: '#721c24',
        borderRadius: '5px',
        textAlign: 'center',
    },
    success: {
        marginTop: '20px',
        padding: '10px',
        backgroundColor: '#d4edda',
        color: '#155724',
        borderRadius: '5px',
        textAlign: 'center',
    },
    loader: {
        marginTop: '20px',
        textAlign: 'center',
        fontSize: '16px',
        color: '#007bff',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: '0',
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modal: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '8px',
        width: '500px',
        maxHeight: '80vh',
        overflowY: 'auto',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    modalHeader: {
        fontSize: '20px',
        marginBottom: '20px',
        color: '#343a40',
        borderBottom: '1px solid #ced4da',
        paddingBottom: '10px',
    },
    modalContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '15px',
    },
    noComponents: {
        fontSize: '14px',
        color: '#721c24',
        textAlign: 'center',
    },
    mappingRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    componentContainer: {
        flex: '1',
        display: 'flex',
        flexDirection: 'column',
        gap: '5px',
    },
    mappingLabel: {
        fontSize: '14px',
        color: '#343a40',
    },
    endpointList: {
        margin: 0,
        paddingLeft: '20px',
        fontSize: '12px',
        color: '#6c757d',
    },
    endpointItem: {
        marginBottom: '2px',
    },
    mappingSelect: {
        flex: '2',
        padding: '6px',
        fontSize: '14px',
        borderRadius: '5px',
        border: '1px solid #ced4da',
        color: '#343a40',
        backgroundColor: '#fff',
    },
    modalActions: {
        marginTop: '20px',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '10px',
    },
    modalButtonCancel: {
        padding: '8px 16px',
        fontSize: '14px',
        color: '#fff',
        backgroundColor: '#6c757d',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
        '&:hover': {
            backgroundColor: '#5a6268',
        },
    },
    modalButtonConfirm: {
        padding: '8px 16px',
        fontSize: '14px',
        color: '#fff',
        backgroundColor: '#28a745',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
        '&:hover': {
            backgroundColor: '#218838',
        },
        '&:disabled': {
            backgroundColor: '#6c757d',
            cursor: 'not-allowed',
        },
    },
    // Цветовые переменные для упрощения
    primary: '#007bff',
    success: '#28a745',
    warning: '#ffc107',
    danger: '#dc3545',
    textDark: '#343a40',
    textMuted: '#6c757d',
    borderLight: '#ced4da',
    lightGray: '#e9ecef',
    dfe6e9: '#dfe6e9',
    e8ecef: '#e8ecef',
    c8d6e5: '#c8d6e5',
    dee2e6: '#dee2e6',
};

export default styles;