// client/src/components/styles.js
const styles = {
    container: {
        padding: '20px',
        maxWidth: '900px',
        margin: '0 auto',
        backgroundColor: '#ffffff',
        borderRadius: '12px',
        boxShadow: '0 4px 24px rgba(0, 0, 0, 0.1)',
        fontFamily: '"Roboto", sans-serif',
    },
    headerSection: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
    },
    title: {
        fontSize: '28px',
        color: '#2c3e50',
        margin: 0,
        fontWeight: 700,
    },
    backButton: {
        padding: '8px 16px',
        fontSize: '14px',
        color: '#ffffff',
        backgroundColor: '#6c757d',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, transform 0.1s',
        '&:hover': { backgroundColor: '#5a6268', transform: 'translateY(-1px)' },
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '16px',
        fontWeight: 600,
        color: '#2c3e50',
    },
    select: {
        padding: '10px',
        fontSize: '14px',
        borderRadius: '8px',
        border: '1px solid #ced4da',
        color: '#2c3e50',
        backgroundColor: '#ffffff',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        '&:focus': { borderColor: '#007bff', boxShadow: '0 0 0 3px rgba(0, 123, 255, 0.2)', outline: 'none' },
    },
    uploadContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '10px',
        backgroundColor: '#f8f9fa',
        borderRadius: '8px',
        border: '1px dashed #ced4da',
    },
    fileInput: {
        flex: 1,
        padding: '8px 0',
        border: 'none',
        background: 'transparent',
        color: '#2c3e50',
        cursor: 'pointer',
    },
    fileName: {
        fontSize: '14px',
        color: '#6c757d',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        maxWidth: '200px',
    },
    jiraInput: {
        padding: '12px',
        fontSize: '14px',
        borderRadius: '8px',
        border: '1px solid #ced4da',
        color: '#2c3e50',
        backgroundColor: '#ffffff',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        '&:focus': { borderColor: '#007bff', boxShadow: '0 0 0 3px rgba(0, 123, 255, 0.2)', outline: 'none' },
    },
    mappingSection: {
        marginTop: '24px',
        padding: '16px',
        backgroundColor: '#f8f9fa',
        borderRadius: '12px',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
        maxHeight: 'calc(100vh - 400px)', // Ограничиваем высоту для скроллинга
        overflowY: 'auto',
    },
    subHeader: {
        fontSize: '20px',
        marginBottom: '16px',
        color: '#2c3e50',
        fontWeight: 600,
    },
    featureLevel: {
        padding: '12px 16px',
        backgroundColor: '#dfe6e9',
        color: '#2c3e50',
        border: '1px solid #ced4da',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    },
    storyLevel: {
        padding: '8px 12px',
        backgroundColor: '#e8ecef',
        color: '#2c3e50',
        border: '1px solid #ced4da',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    },
    toggleIcon: {
        marginRight: '8px',
        color: '#6c757d',
    },
    folderName: {
        fontWeight: '600',
    },
    nestedFolders: {
        marginTop: '8px',
        transition: 'max-height 0.3s ease',
        overflow: 'hidden',
    },
    footer: {
        marginTop: '24px',
        paddingTop: '16px',
        borderTop: '1px solid #ced4da',
        position: 'sticky',
        bottom: 0,
        backgroundColor: '#ffffff',
        zIndex: 10,
    },
    submitButton: {
        padding: '12px 24px',
        fontSize: '16px',
        color: '#ffffff',
        backgroundColor: '#28a745',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, transform 0.1s',
        '&:hover': { backgroundColor: '#218838', transform: 'translateY(-2px)' },
        '&:disabled': { backgroundColor: '#6c757d', cursor: 'not-allowed' },
    },
    error: {
        marginTop: '24px',
        padding: '12px',
        backgroundColor: '#ffebee',
        color: '#721c24',
        borderRadius: '8px',
        textAlign: 'center',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    },
    success: {
        marginTop: '24px',
        padding: '12px',
        backgroundColor: '#d4edda',
        color: '#155724',
        borderRadius: '8px',
        textAlign: 'center',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    },
    successLink: {
        display: 'block',
        marginTop: '8px',
        color: '#007bff',
        textDecoration: 'none',
        '&:hover': { textDecoration: 'underline' },
    },
    loader: {
        marginTop: '24px',
        textAlign: 'center',
    },
    loaderSpinner: {
        display: 'inline-block',
        position: 'relative',
        width: '40px',
        height: '40px',
    },
    spinner: {
        boxSizing: 'border-box',
        display: 'block',
        position: 'absolute',
        width: '32px',
        height: '32px',
        border: '4px solid #007bff',
        borderRadius: '50%',
        animation: 'spin 1s linear infinite',
        borderColor: '#007bff transparent transparent transparent',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modal: {
        backgroundColor: '#ffffff',
        padding: '24px',
        borderRadius: '12px',
        width: '800px',
        maxHeight: '90vh',
        overflowY: 'auto',
        boxShadow: '0 8px 24px rgba(0, 0, 0, 0.15)',
    },
    modalHeader: {
        fontSize: '24px',
        marginBottom: '20px',
        color: '#2c3e50',
        fontWeight: 700,
        borderBottom: '2px solid #ced4da',
        paddingBottom: '16px',
    },
    modalContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        maxHeight: 'calc(90vh - 120px)',
        overflowY: 'auto',
    },
    noComponents: {
        fontSize: '16px',
        color: '#721c24',
        textAlign: 'center',
        padding: '16px',
        backgroundColor: '#ffebee',
        borderRadius: '8px',
    },
    mappingRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        padding: '12px',
        backgroundColor: '#f8f9fa',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    },
    componentContainer: {
        flex: 1,
        display: 'flex',
    },
    mappingLabel: {
        fontSize: '16px',
        fontWeight: 600,
        color: '#2c3e50',
    },
    endpointList: {
        margin: 0,
        paddingLeft: '20px',
        fontSize: '14px',
        color: '#6c757d',
        listStyle: 'none',
    },
    endpointItem: {
        marginBottom: '8px',
    },
    modalFooter: {
        marginTop: '20px',
        paddingTop: '16px',
        borderTop: '2px solid #ced4da',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '16px',
    },
    modalButtonCancel: {
        padding: '12px 24px',
        fontSize: '16px',
        color: '#ffffff',
        backgroundColor: '#6c757d',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, transform 0.1s',
        '&:hover': { backgroundColor: '#5a6268', transform: 'translateY(-2px)' },
    },
    modalButtonConfirm: {
        padding: '12px 24px',
        fontSize: '16px',
        color: '#ffffff',
        backgroundColor: '#28a745',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, transform 0.1s',
        '&:hover': { backgroundColor: '#218838', transform: 'translateY(-2px)' },
        '&:disabled': { backgroundColor: '#6c757d', cursor: 'not-allowed' },
    },
    // Цветовые переменные
    primary: '#007bff',
    success: '#28a745',
    warning: '#ffc107',
    danger: '#dc3545',
    textDark: '#2c3e50',
    textMuted: '#6c757d',
    borderLight: '#ced4da',
    lightGray: '#e9ecef',
    dfe6e9: '#dfe6e9',
    e8ecef: '#e8ecef',
    c8d6e5: '#c8d6e5',
    dee2e6: '#dee2e6',
    // Анимация для спиннера
    '@keyframes spin': {
        '0%': { transform: 'rotate(0deg)' },
        '100%': { transform: 'rotate(360deg)' },
    },
};

export default styles;