const styles = {
    container: {
        padding: '24px',
        maxWidth: '1000px',
        margin: '0 auto',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        boxSizing: 'border-box',
        backgroundColor: 'rgba(255, 255, 255, 0.98)',
        backdropFilter: 'blur(20px)',
        borderRadius: '6px',
        boxShadow: '0 20px 50px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.02)',
        fontFamily: '"Inter", "Outfit", "Roboto", sans-serif',
        border: '1px solid rgba(255, 255, 255, 0.8)',
        overflow: 'hidden',
    },
    headerSection: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '32px',
        paddingBottom: '20px',
        borderBottom: '1px solid #f1f5f9',
    },
    title: {
        fontSize: '32px',
        color: '#0f172a',
        margin: 0,
        fontWeight: 800,
        letterSpacing: '-0.02em',
        background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        textShadow: 'none'
    },
    backButton: {
        padding: '10px 20px',
        fontSize: '14px',
        fontWeight: 600,
        color: '#475569',
        backgroundColor: '#fff',
        border: '1px solid #e2e8f0',
        borderRadius: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '28px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    label: {
        fontSize: '14px',
        fontWeight: 600,
        color: '#475569',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        marginBottom: '4px',
    },
    select: {
        width: '100%',
        boxSizing: 'border-box',
        margin: 0,
        padding: '14px 16px',
        fontSize: '15px',
        borderRadius: '14px',
        border: '1px solid #e2e8f0',
        color: '#0f172a',
        backgroundColor: '#f8fafc',
        transition: 'all 0.2s ease',
        appearance: 'none',
        backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' fill=\'none\' viewBox=\'0 0 24 24\' stroke=\'%2364748b\'%3E%3Cpath stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke-width=\'2\' d=\'M19 9l-7 7-7-7\' /%3E%3C/svg%3E")',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'right 16px center',
        backgroundSize: '18px',
        cursor: 'pointer',
    },
    uploadContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        padding: '10px 20px',
        backgroundColor: '#f8fafc',
        borderRadius: '16px',
        border: '2px dashed #cbd5e1',
        transition: 'all 0.2s ease',
        cursor: 'pointer',
        width: '100%',
        boxSizing: 'border-box',
        minHeight: '54px'
    },
    fileInput: {
        flex: 1,
        fontSize: '14px',
        color: '#475569',
        cursor: 'pointer',
    },
    fileName: {
        fontSize: '13px',
        fontWeight: 500,
        color: '#6366f1',
        backgroundColor: '#eef2ff',
        padding: '4px 12px',
        borderRadius: '8px',
        maxWidth: '300px',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    mappingSection: {
        marginTop: '32px',
        padding: '24px',
        backgroundColor: '#fff',
        borderRadius: '20px',
        border: '1px solid #f1f5f9',
        boxShadow: '0 4px 12px rgba(15, 23, 42, 0.03)',
        maxHeight: '600px',
        overflowY: 'auto',
    },
    modalButtonCancel: {
        padding: '12px 24px',
        fontSize: '14px',
        fontWeight: 600,
        color: '#475569',
        backgroundColor: '#fff',
        border: '1px solid #cbd5e1',
        borderRadius: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    },
    modalButtonSave: {
        padding: '12px 24px',
        fontSize: '14px',
        fontWeight: 600,
        color: '#ffffff',
        background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
        border: 'none',
        borderRadius: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        boxShadow: '0 4px 12px rgba(37, 99, 235, 0.2)',
    },

    subHeader: {
        fontSize: '22px',
        color: '#0f172a',
        margin: 0,
        fontWeight: 700,
        letterSpacing: '-0.02em',
        background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        textShadow: 'none'
    },
    footer: {
        marginTop: '40px',
        paddingTop: '24px',
        borderTop: '1px solid #f1f5f9',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '20px',
    },
    submitButton: {
        padding: '16px 40px',
        fontSize: '16px',
        fontWeight: 700,
        color: '#ffffff',
        background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
        border: 'none',
        borderRadius: '16px',
        cursor: 'pointer',
        transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        boxShadow: '0 10px 25px -5px rgba(16, 185, 129, 0.4)',
        width: '100%',
        maxWidth: '400px',
    },
    modalButtonConfirm: {
        padding: '12px 24px',
        fontSize: '14px',
        fontWeight: 600,
        color: '#ffffff',
        background: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)', // Индиго/фиолетовый акцент (под цвет primary)
        border: 'none',
        borderRadius: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        boxShadow: '0 4px 12px rgba(79, 70, 229, 0.3)',
    },

    error: {
        padding: '14px 20px',
        backgroundColor: '#fef2f2',
        border: '1px solid #fee2e2',
        color: '#ef4444',
        borderRadius: '12px',
        fontSize: '14px',
        fontWeight: 500,
        textAlign: 'center',
        width: '100%',
    },
    success: {
        padding: '14px 20px',
        backgroundColor: '#f0fdf4',
        border: '1px solid #dcfce7',
        color: '#10b981',
        borderRadius: '12px',
        fontSize: '14px',
        fontWeight: 500,
        textAlign: 'center',
        width: '100%',
    },
    loader: {
        display: 'flex',
        justifyContent: 'center',
        padding: '20px',
    },
    loaderSpinner: {
        display: 'inline-flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    spinner: {
        width: '20px',
        height: '20px',
        border: '3px solid rgba(255, 255, 255, 0.3)',
        borderRadius: '50%',
        borderTopColor: '#ffffff',
        animation: 'spin 1s linear infinite',
        display: 'inline-block',
        boxSizing: 'border-box'
    },

    primary: '#6366f1',
    successColor: '#10b981',
    warningColor: '#f59e0b',
    dangerColor: '#ef4444',
    textDark: '#0f172a',
    textMuted: '#64748b',
};

export default styles;
