services:
  allure-test-inspector:
    image: git.abanking.ru:4567/vpoliakov/allure-test-inspector:main
    restart: always
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - allure-test-net

  tia-mapping-service:
    depends_on:
      - postgresql
    image: git.abanking.ru:4567/vpoliakov/allure-test-inspector/tia-mapping-service:main
    restart: always
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - allure-test-net

  postgresql:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    networks:
      - allure-test-net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  allure-test-net: