FROM node:18-alpine

RUN apk update && apk add --no-cache postgresql-client curl

WORKDIR /app/bdd-server

COPY bdd-server/package*.json ./
RUN npm install --legacy-peer-deps --production

COPY bdd-server/ ./

WORKDIR /app
COPY server/cloudruClient.mjs server/cloudruClient.mjs
COPY server/config.json server/config.json
COPY shared/ shared/

WORKDIR /app/bdd-server
RUN cp -r node_modules /app/

WORKDIR /app/bdd-server

EXPOSE 5002

CMD ["npm", "start"]
