# Stage 1: Build client
FROM node:18-alpine as frontend-builder

WORKDIR /usr/src/app/client

# Копируем package.json и package-lock.json
COPY client/package*.json ./

# Даем права на все файлы в рабочей директории
RUN chmod -R 755 /usr/src/app/client

# Очистка кеша npm
RUN npm cache clean --force

# Устанавливаем зависимости
RUN npm install --legacy-peer-deps --force

# Билдим клиент
COPY client/ .
RUN chmod -R 755 /usr/src/app/client/node_modules
RUN ./node_modules/.bin/react-scripts build

# Stage 2: Build backend and serve static files
FROM node:18-alpine as backend

WORKDIR /usr/src/app

# Копируем серверные файлы
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY server/ /usr/src/app/server/

# Скопировать билд React-приложения в папку для статики
COPY --from=frontend-builder /usr/src/app/client/build ./client/build

# Устанавливаем пакет serve для обслуживания статики клиента
RUN npm install -g serve

# Expose порты
EXPOSE 3000 5000

# Запуск как сервера API, так и клиента через serve
CMD ["sh", "-c", "node server/server.js & serve -s client/build -l 3000"]
